version: '3.8'

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_USERNAME}-TaskManagement-backend:latest
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/taskmanagement
      - JWT_SECRET=your_jwt_secret
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - SMTP_USER=your_email@gmail.com
      - SMTP_PASS=your_app_password
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_USERNAME}-TaskManagement-frontend:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 